version: '3.8'
services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
    environment:
      - NAME=AI Tutor Backend
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    environment:
      - NODE_ENV=dev