version: '3.8'
services:
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    volumes:
      - ./Backend:/app
    environment:
      - NAME=AI Tutor Backend
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
    environment:
      - NODE_ENV=development